### ISSUE TITLE
Android release build crashes

### ISSUE THREAD

**Issue by raynor85** [iyegoroff/react-native-color-matrix-image-filters#3] opened 2018-09-21 16:32 UTC
react-native-color-matrix-image-filters: 1.0.8
react-native: 0.57.0

When I create a build with android with assembleRelease and I install it on the emulator or on a real device, the app crashes.

**Comment by iyegoroff** [comment] 2018-09-21 16:45
Does `react-native log-android` produce any crash log?

**Comment by raynor85** [comment] 2018-09-24 10:42
Ok I have tried to switch Java version, but the problem still occurs. 
It is worth noting that this happens only when I generate the signed APK (gradlew installRelease), it doesn't happen with the debug release (gradlew installDebug).

This is the log from ```react-native log-android```
```
E ReactNativeJS: Invalid attempt to destructure non-iterable instance
E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by raynor85** [comment] 2018-09-24 11:51
The problem is that I have to codesign your example to have a coherent test. As I said before, gradlew installDebug works just fine

**Comment by raynor85** [comment] 2018-09-24 13:56
```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js","targetModuleName":"./out/App","message":"Unable to resolve module `./out/App` from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`: The module `./out/App` could not be found from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`. Indeed, none of these files exist:\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`","errors":[{"description":"Unable to resolve module `./out/App` from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`: The module `./out/App` could not be found from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`. Indeed, none of these files exist:\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`"}],"name":"Error","stack":"Error: Unable to resolve module `./out/App` from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`: The module `./out/App` could not be found from `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/index.js`. Indeed, none of these files exist:\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`\n  * `/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/out/App/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`\n    at ModuleResolver.resolveDependency (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:697)\n    at ResolutionRequest.resolveDependency (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)\n    at DependencyGraph.resolveDependency (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)\n    at Object.resolve (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/lib/transformHelpers.js:180:25)\n    at dependencies.map.result (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)\n    at /Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33\n    at Generator.next (<anonymous>)\n    at step (/Users/ruben/Downloads/react-native-color-matrix-image-filters-master/MatrixFilterConstructor/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764
```

**Comment by iyegoroff** [comment] 2018-09-24 16:02
Did you follow the instruction from example [readme](https://github.com/iyegoroff/react-native-color-matrix-image-filters/blob/master/MatrixFilterConstructor/README.md)? Only version that was installed from npm should contain files like './out/App'.

**Comment by mllrmat** [comment] 2018-09-27 10:12
I got the same problem. I followed the instructions provided and in debug mode everything works find. Same on iOS. Just on Android the release app crashes on boot. 

Stacktrace: 
`09-27 11:25:49.141 9884-9904/by.gets.clientapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: by.gets.clientapp, PID: 9884
    com.facebook.react.common.JavascriptException: Invalid attempt to destructure non-iterable instance, stack:
    nonIterableRest@11:3833
    toArray@11:4328
    s@1271:772
    <unknown>@1271:1566
    <unknown>@1271:1544
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@1270:71
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@1269:204
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@1268:315
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@898:749
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@311:477
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@12:81
    v@2:1489
    d@2:879
    o@2:435
    global code@1278:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
`
react:  16.5.0
react-native: 0.57.0

**Comment by Christian-Athom** [comment] 2018-09-27 13:13
Same error as @mllrmat on react-native: 0.56.0

**Comment by Christian-Athom** [comment] 2018-09-28 09:30
The errors i see when building are: 

Unable to strip library '.../android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/armeabi/libicu_common.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

Unable to strip library '.../android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/armeabi/libimagepipeline.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

Could this be related to: https://github.com/android-ndk/ndk/issues/700 ?

**Comment by iyegoroff** [comment] 2018-10-03 02:11
Closing this because I can't reproduce release version crash. Feel free to reopen it if you have a reproducible example. 

Also I created a Docker [image](https://github.com/iyegoroff/react-native-color-matrix-image-filters/tree/master/MatrixFilterConstructor#building-signed-release-apk-with-docker) which can be used to generate signed apks.

**Closed by iyegoroff** 2018-10-03 02:11 UTC

**Comment by Christian-Athom** [comment] 2018-10-05 07:37
@mllrmat A fix for this problem was just merged into master, you can check if this also fixed your problem.

**Comment by raynor85** [comment] 2018-10-07 18:33
Yeah, I can confirm that the fix merged to master fixed the build on
android. Well done!
